name: flutter_design_patterns
description: App which can help to learning design patterns and implement them with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  effective_dart: ^1.3.1
  yaml: ^3.1.0
  provider: ^6.0.0
  flutter_markdown: ^0.6.6
  xml: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  dart_code_metrics: ^4.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/config/config_design_patterns.json
    - assets/markdown/