name: flutter_design_patterns
description: App which can help to learning design patterns and implement them with Flutter.
version: 1.0.3+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  effective_dart: ^1.3.1
  yaml: ^3.1.0
  provider: ^6.0.0
  flutter_markdown: ^0.6.6
  xml: ^5.3.0
  faker: ^2.0.0
  font_awesome_flutter: ^9.1.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.6
  path: ^1.8.0
  flutter_native_splash: ^1.3.1
  shared_preferences: ^2.0.8
  day_night_switcher: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  dart_code_metrics: ^4.1.0

flutter_native_splash:
  image: "assets/images/app_icon.png"
  color: "8E93B3"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/config/config_design_patterns.json
    - assets/markdown/